### ISSUE TITLE
NameError: undefined local variable or method `extensions'

### ISSUE THREAD

**Issue by GSI** [middleman/middleman-sprockets#111]
*Middleman 4.1.6 + middleman-sprockets (4.0.0.rc.2)*

I am unsure if this is a bug or if I'm just misunderstanding something:

In foo.js.erb I have this:
`var availabeLanguages = <%= extensions[:i18n].options.langs %>;`

When opening http://0.0.0.0:4567/javascripts/foo.js I see this text:

```
throw Error("NameError: undefined local variable or method `extensions' for #<#<Class:0x005630a336b580>:0x005630a30d4b28>\n  on line 30 of /path/to/source/javascripts/foo.js.erb)")
```

How may I access `extensions` (or `config`) in this context?

**Comment by tdreyno** [comment]
`app.extensions` should do the trick.

That said, it does make sense to expose that at `extensions` in both environment, so I will add that going forward

**Comment by tdreyno** [comment]
Ah, I see, this is a problem with the Sprockets environment, not Middleman's. Can you move this ticket over here: https://github.com/middleman/middleman-sprockets

I've exposed `extensions` in config.

**Comment by GSI** [comment]
Works like a charm now. Thank you, Thomas.
