### ISSUE TITLE
Parallel build stuck with middleman-sprockets and mini_racer gems

### ISSUE THREAD

**Issue by le0pard** [middleman/middleman-sprockets#117]
Hello. Found little issue with middleman-sprockets 4.0.0 and mini_racer 0.1.4.

Command `middleman server` works without any problem, but if I run `middleman build`, it have stuck:

```
...
== Finishing Request: javascripts/vendors/modernizr.js (0.0s)
== Request: /stylesheets/application.css
== Finishing Request: stylesheets/application.css (0.0s)
== Request: /stylesheets/vendors/highlight/railscasts.css
== Finishing Request: stylesheets/vendors/highlight/railscasts.css (0.0s)
== Running manipulator: sitemap_move_files (101)
== Running manipulator: collections (110)
== Running manipulator: routing (130)
== Prerendering CSS
== Request: /stylesheets/application-b6b43a1c.css
== Request: /stylesheets/vendors/highlight/railscasts-dc837e3e.css
== Finishing Request: stylesheets/vendors/highlight/railscasts-dc837e3e.css (0.01s)
== Finishing Request: stylesheets/application-b6b43a1c.css (0.02s)
      create  build/stylesheets/vendors/highlight/railscasts-dc837e3e.css
      create  build/stylesheets/application-b6b43a1c.css
```

If I use `middleman build --no-parallel` it works without problem. Also, if I changed to `therubyracer` all works fine with parallel build.

Repo with app: https://github.com/le0pard/pgtune (you can try to replace `therubyracer` to `mini_racer`, make `bundle` and try `middleman build`)

**Comment by tdreyno** [comment]
Weird, seems like they would be fine with their claim of Threadsafety (https://github.com/discourse/mini_racer#threadsafe).

Sounds like a bug with `mini_racer` if the normal rubyracer they are trying to emulate works.

**Comment by le0pard** [comment]
@tdreyno `--verbose` doesn't show enough information, so not clear, why it is happened. I can try to do something else to provide more info, just need to know what to do.

**Comment by tdreyno** [comment]
`--instrument` is also a helpful flag.

I've definitely seen issues using ExecJS. therubyracer and Node backends seem to do best

**Comment by le0pard** [comment]
Ok, thanks. Will check with ExecJS.
