### ISSUE TITLE
asset hash

### ISSUE THREAD

**Issue by lifeiscontent** [middleman/middleman-sprockets#120]
I'm wondering if there is a way you can generate a hash in the filename like rails does of assets.

such as: application-1234i9jasetgij31254ijwetr.js

so that I don't have to worry about timestamps on my static assets for caching.

**Comment by stevenosloan** [comment]
Yep! You can do that with the `asset_hash` extension in Middleman. Just add `activate :asset_hash` in config.rb. There's a bit more info [in the docs](https://middlemanapp.com/advanced/improving_cacheability/#uniquely-named-assets)

**Comment by lifeiscontent** [comment]
@stevenosloan awesome, thank you!
