### ISSUE TITLE
Adding middleman-sprockets and activating them results in SCSS file being rendered verbatim and  not processed

### ISSUE THREAD

**Issue by andreimoment** [middleman/middleman-sprockets#134]
## Expected behavior and actual behavior
Created a new project with middleman `init mm-4-test`

Changed the Gemfile to
```
source 'https://rubygems.org'

gem 'middleman', '~> 4.2'
gem 'middleman-sprockets' # added this line
gem 'middleman-autoprefixer', '~> 2.7'
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby, :x64_mingw]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw, :x64_mingw]
```

and added

`activate :sprockets` to config.rb

then `bundle update`

Running `middleman s` shows

```
...
== Sprockets will render css with SassC
```

but going to `http://localhost:4567/stylesheets/site.css`

loads the `/source/stylesheets/site.css.scss` without processing it

```
body {
  background-color: #fbc547;
  color: #333;
  font-family: -apple-system, BlinkMacSystemFont, "Avenir Next", "Avenir",
    "Segoe UI", "Lucida Grande", "Helvetica Neue", "Helvetica", "Fira Sans",
    "Roboto", "Noto", "Droid Sans", "Cantarell", "Oxygen", "Ubuntu",
    "Franklin Gothic Medium", "Century Gothic", "Liberation Sans", sans-serif;
  padding: 18vh 1rem;
  text-align: center;
}

a {
  color: rgba(#000, 0.7);

  &:focus,
  &:hover {
    color: rgba(#000, 0.6);
  }
}

.middleman-logo {
  margin-bottom: 1rem;
  width: 10rem;
}
```

## Steps to reproduce the problem (from a clean middleman installation) or example repo

https://github.com/andreimoment/mm-4-test

## Additional information

- Ruby version: 2.5.5
- Middleman version: 4.3.11
- Middleman Sprockets version: 4.1.1
- OS version: MacOS 10.15.7

**Comment by tdreyno** [comment]
Sass support is native to MM4 and doesn't need sprockets. middleman-sprockets has been abandoned for about 5 years, I would not suggest adding it to projects.

You could try only activating it for JS if that helps:

```
activate :sprockets, supported_output_extensions: ['.js']
```

**Comment by andreimoment** [comment]
This makes sense... I'll remove sprockets. 

By the way thank you for the long term work on middlemanapp! It is my favorite tool for front end prototyping.
