### ISSUE TITLE
font-url not working when asset_hash and asset_host activated at the same time

### ISSUE THREAD

**Issue by tmaier** [middleman/middleman-sprockets#46]
cristianferrarig/font-awesome-middleman#3

https://github.com/cristianferrarig/font-awesome-middleman uses `font-url`.

`font-url` uses the hashed file name when asset_hash is activated.

But when I also activate asset_host, I get the `font-url` with the correct host, but without the hashed file name

**Comment by stevenosloan** [comment]
Closing this due to age (IIRC this was addressed in middleman-core), we do have a test case [here](https://github.com/middleman/middleman-sprockets/blob/master/features/test_cases/asset_hash.feature#L59-L72) I believe covers this.

If you continue to run into this please re-open.
