### ISSUE TITLE
new CSS file not spotted

### ISSUE THREAD

**Issue by Nowaker** [middleman/middleman-sprockets#62]
main.css.scss:

```
@import 'pages/*';
```

Middleman / Sprockets doesn't spot a new file once added to `pages/` directory. I have to restart Middleman server.

**Comment by LandonSchropp** [comment]
+1 I have this same issue.

**Comment by alekseyg** [comment]
I have a similar issue where Middleman won't reload any of the changes in Sass, even though livereload does reload the CSS file. Once I stop middleman server and relaunch it, then it recompiles my Sass.

**Comment by tdreyno** [comment]
Version numbers please :)

**Comment by alekseyg** [comment]
Middleman 4.0.0
Middleman Sprockets 4.0.0.rc.1

**Comment by alekseyg** [comment]
I was able to work around this issue. Before I had an `app.css` file, which was purely a manifest file, including some libraries, and then my main SCSS file. After renaming it to `app.css.scss`, and still importing the libraries via sprockets, but the Sass via Sass's `@import`, it started working as expected.

So, here's an example manifest file before:
```css
/*
 *= require fancybox
 *= require _mysassfile
 */
```

After (as app.css.scss):
```scss
//= require fancybox
@import "mysassfile";
```

**Comment by alekseyg** [comment]
My guess is that my issue is probably different from @Nowaker's, but it seemed to be related until I figured out a way to work around it. Perhaps the issue with the manifest file should be opened as a new issue if there isn't something on it already.

**Comment by Nowaker** [comment]
Feel free to hijack my issue, it's too old to even think of mine. :-)

**Comment by tdreyno** [comment]
Ah, yes, the additional suffixes are now required in v4.

**Comment by alekseyg** [comment]
Sure, but I expected it to work like Rails, where you can import CSS, Sass, or whatever else in the manifest file, which can be a plain CSS file. It does work, but it requires reloading the server to apply any changes to the Sass unless you have the manifest file be a Sass file as well. I suppose the workaround is fine in most cases, but it still seems that Sprockets isn't working the way it does in Rails, and could cause issues for someone who chooses to use something other than Sass. IOW, my problem is solved by now and I'm happy, but some bug somewhere is probably lurking. :)

**Comment by andreamoro** [comment]
@alekseyg any chance to post few lines of code of how you have imported the file?
I changed the manifest file, renamed it, but now I get the following error

"Error file not found or unable or unreadable: initialise" followed by the path of my file.

**Comment by alekseyg** [comment]
@andreamoro I have an example and explanation in a previous comment here: https://github.com/middleman/middleman-sprockets/issues/62#issuecomment-171803558
If you have any specific questions about it, let me know.

**Comment by andreamoro** [comment]
@alekseyg I've seen and started from there, but my pipelined file is empty.
Any idea?

**Comment by andreamoro** [comment]
Ok, got the problems. Also the imported files should have the .scss extension, whereas I was leaving it as .css

Just a question. Is this mean I am using sprocket or Sass? I believe the latter is the answer, but I'm fairly a newbie re these new web dev technologies.

**Comment by alekseyg** [comment]
In the case of my example `//= require fancybox` uses Sprockets, while `@import "mysassfile";` uses Sass. The reason I still use Sprockets on Fancybox is because the gem still has it as a regular CSS file, if I remember correctly, and I don't change its contents, so this bug doesn't bother me with that file. As for Bootstrap and other gems which do have Sass files, I always import those using Sass, so I can tweak variables and whatnot.

**Comment by robertwbradford** [comment]
I just ran across this too. It looks like if you are trying to import a `.css` file, you have to explicitly add the `.css`. For example:
```
@import "some/css-file.css";
```
Before, just the following would work:
```
@import "some/css-file";
```
Is this documented somewhere?

**Comment by alekseyg** [comment]
@robertwbradford I wouldn't recommend importing plain CSS files in Sass. The reason is because it does not concatenate the CSS into the compiled Sass file like it does with Sass, but actually puts a CSS `@import` directive into your final CSS. Basically the behavior between `@import "some-file.scss"` and `@import "some-file.css"` is very different.

**Comment by robertwbradford** [comment]
@alekseyg I remember hearing that before now that you say that. I'm going to rename them to use `.scss`. Thanks!

**Comment by stevenosloan** [comment]
Is anyone still seeing this issue on master? (keeping in mind you'll need sass-globbing to use globs https://github.com/middleman/middleman/issues/1627)

**Comment by stevenosloan** [comment]
I've been able to replicate the original issue with a [test case](https://gist.github.com/stevenosloan/36489013183350047f2cb9a85c07436b). It looks like the issue's in how dependencies are tracked (or not) between sass and the sass-globbing gem. When looking for the dependencies, the only "imported file" [here](https://github.com/sass/sass/blob/63586f1e51c0aec47a7afcc8cd17aa03f32f0a29/lib/sass/engine.rb#L346-L349) is `**/*` so the cache doesn't get busted on other files changing.

Without changing how sass checked dependencies (or ImportNode supporting multiple imports), I don't see a clear path to fix this issue. (and I don't think changes to sass will happen, it's been turned down [a few](https://github.com/sass/sass/issues/1888) [times](https://github.com/sass/sass/issues/1517))

I'm going to add a note about this to the test case and close it for now, if we get enough interest in it (or a clean solution) I'll open it back up.
