### ISSUE TITLE
Issue with `import_asset` in middleman server mode

### ISSUE THREAD

**Issue by dcosson** [middleman/middleman-sprockets#73]
Hi, I'm running into an issue when including assets with `sprockets.import_asset` in my middleman `config.rb`.

I'm using a bower library that includes a couple of images and fonts in addition to the js and scss. The library uses scss functions like `image-url` to access these assets, so the page is looking for them in my root images dir `/images`.  Reading through [this section](http://middlemanapp.com/basics/asset-pipeline/#sprockets-import-path) of the docs it seems like sprockets import_asset is what I need to copy over the relevant assets.

I added a line like:

```
sprockets.import_asset('slick.js/slick/ajax-loader.gif') {|x| 'images/ajax-loader.gif'}
```

When I run `middleman build` it's working and copying the image to the expected location. But when running `middleman server` mode, I still get a 404 for the asset.

The weird thing is it's a different page than for something that doesn't exist at all - before I added that line I was getting a 404 with an html page saying `File Not Found ... If this is an an asset from a gem, add sprockets.import_asset 'ajax-loaders.gif' to your config.rb` which is an error from middleman-sprockets, but now I get a 404 and the non-html text "Not Found".

Any idea what's going on?

**Comment by tdreyno** [comment]
Nope, but it definitely sounds like a bug. Will look in to it.

**Comment by dcosson** [comment]
Actually it looks like this has been fixed, sorry for the confusion. I'm using the latest middleman so assumed I had the latest code but my middleman-sprockets was at 3.3.x, when I manually updated to 3.4.1 it's now working.
