### ISSUE TITLE
Use Sprockets version 3 (instead of version 2)

### ISSUE THREAD

**Issue by alem0lars** [middleman/middleman-sprockets#77]
It would be very great if middleman-sprockets will support Sprockets version 3 and above..

This is because:
1. **Use libraries which requires Sprockets 3 (or above)**, like `middleman-es6`. This is needed if we want to effectively use ES6 in middleman projects without hacks or dirty solutions.
2. To have dependencies up-to-date.

**Comment by tdreyno** [comment]
This would be great. Make a PR

**Comment by zackp30** [comment]
It appears this has already been done? The gemspec states vversion 3 for Sprockets, so should this be closed?

**Comment by tdreyno** [comment]
Not released yet, but done
