### ISSUE TITLE
Deleting an asset silently kills file watcher thread.

### ISSUE THREAD

**Issue by noniq** [middleman/middleman-sprockets#78]
Steps to reproduce (using middleman 3.3.10):
  1. Generate new project: `middleman init bugreport && cd bugreport`
  3. Start server with verbose output: `middleman --verbose`
  4. Remove one of the images in `source/images/` while middleman is running.
  5. => Changes to any file are now no longer recognized.

As far as I understand this is what's happening:

 * After the image is deleted `Middleman::Sitemap::Store.ensure_resource_list_updated!` gets called, which then loops over `@resource_list_manipulators`, calling `#manipulate_resource_list` on each manipulator, eventually reaching `Middleman::SprocketsExtension`.
 * `Middleman::SprocketsExtension.manipulate_resource_list` loops over `environment.imported_assets`, which at this stage still contains an entry for the removed file.
 * `Middleman::Sprockets::Asset#initialize` gets called, with `lookup_path` referencing the no longer existing file.
 * `sprockets.resolve(lookup_path)` raises `Sprockets::FileNotFound`
 * This exception is never rescued, thus the file watcher thread terminates. As the exception happens in a thread, there is no backtrace in the terminal either.
 * (The `raise` statement in [line 14](https://github.com/middleman/middleman-sprockets/blob/v3-stable/lib/middleman-sprockets/asset.rb#L14) is probably dead code: If the asset does not exist, an exception will already be raised in line 13).

See https://gist.github.com/noniq/8715581ea244f59f9597 for the complete `Gemfile.lock` and list of stackframes (as reported by byebug).

(I originally stumbled upon this issue in a project using the blog extension: Article URLs suddenly stopped working after I deleted an image. Turns out that this happens because the file watcher thread terminates before `Middleman::Blog::BlogData#manipulate_resource_list` gets called, and so the resource list never gets updated with the article permalinks. Took me quite a while to figure THAT one out …)

**Comment by tdreyno** [comment]
Wonderful bug tracking @noniq, I'll dig in today and get this sorted out.

**Comment by tdreyno** [comment]
Point your `Gemfile ` at `master` and see if this solves your issues.

**Comment by noniq** [comment]
Seems fixed, thanks for the quick response! \o/
