### ISSUE TITLE
 Asset Pipeline isn't working for coffeescript files

### ISSUE THREAD

**Issue by r007** [middleman/middleman-sprockets#79]
Okay, let's say I want to include my coffeescript file using require. But if I simply write
```coffee
//=require "_ajaxcomments"
```
It'll give me an error.
```console
SyntaxError: [stdin]:262:3: unexpected //=
```
I wish I could import my javascript file using ```#=require``` or something like that, but so far I see that sprockets doesn't understand such statements.

**Comment by Arcovion** [comment]
Sprockets does understand the `#= require foo` syntax for CoffeeScript:
https://github.com/sstephenson/sprockets#supported-comment-types

**Comment by r007** [comment]
Okay, I figured out my problem. I should have put it in the beginning of file :)
