### ISSUE TITLE
Isn't it activated by default?

### ISSUE THREAD

**Issue by fullofcaffeine** [middleman/middleman-sprockets#81]
I was under the impression I didn't need to actually add this gem to the Gemfile and activate it as a Middleman plugin. When I call the sprockets method in the config file, it returns a:

```
#<Middleman::Sprockets::ConfigOnlyEnvironment:0x007fa379fcc730 @imported_assets=[...
```

Meaning it's already loaded, right? What's the purpose of this gem, then?

**Comment by akshayrawat** [comment]
The Middleman gem [depends](https://github.com/middleman/middleman/blob/v3-stable/middleman/middleman.gemspec#L22) on Middleman Sprockets gem. So you don't need to mention it in your Gemfile and install it. You should also be able to see [this dependency](https://github.com/aspleenic/ruby_karaoke/blob/master/Gemfile.lock#L58) in your Gemfile.lock file.

**Comment by tdreyno** [comment]
Yes, this gem is included in `middleman`'s dependencies by default. It's separate so we can manage release cycles and bug tracking more easily.
