### ISSUE TITLE
Middleman only builds the first file mentioned in bower.json's main section.

### ISSUE THREAD

**Issue by akshayrawat** [middleman/middleman-sprockets#82]
I'm not sure if this is intentional. When using Middleman (3.3.12) + Bower, if a Bower component has more than 1 file listed in the `main` section of bower.json, only the first file gets built.

__Example:__

The main section of Foundation [bower.json](https://github.com/components/foundation/blob/master/bower.json#L4) specifies 3 files. However during build only the first file gets built/copied ([verbose build output](https://gist.github.com/akshayrawat/0023a83720c31bfd54e6)).

"css/foundation.css" >  build/stylesheets/foundation/css/foundation.css.

It missed "js/fountain.js". For another package, it similarly misses font files which I need copied to the build folder.

`config.rb`

```ruby
sprockets.append_path(File.join "#{root}", "bower_components")
sprockets.import_asset "foundation"
```

Maybe I'm mis-reading this piece of documentation:

>If you tell sprockets just about the name of the component, it will make thos files available which are given in the main-section of the bower.json-file.

By _available_, does this mean that it would not be copied to the build output, but just be available for a sprockets require? If so then, is there something which would copy assets like fonts, imgs (from standard bower component folders) to the build output. (without having to scan those all bower_components  folders to do a `import_asset` for each font, img.)

A minimal repo to reproduce this problem [is here](https://github.com/akshayrawat/mm-bug-test-1). When running `middleman build`, I expect to see `js/fountain.js` get copied (like foundation.css).

Any pointers on this would be much appreciated.

**Comment by tdreyno** [comment]
I think this is how the upstream Sprockets code handles `bower.json`, but I'd have to double check.

I think the way it is supposed to work is that your JS/CSS depends on the assets they require, including fonts and images, then only those assets which are necessary are imported. I'm not a huge fan of the Asset Pipeline, but I think that's how it works.

**Comment by maxmeyer** [comment]
> I'm not a huge fan of the Asset Pipeline, but I think that's how it works.

@tdreyno Any other suggestion what to use instead?

**Comment by tdreyno** [comment]
I personally use webpack, but I don't really think there is an industry standard yet.

**Comment by maxmeyer** [comment]
Thanks for the tip.

**Comment by stevenosloan** [comment]
Hey guys, closing this one out for now -- I've added a link to the readme to a feature explaining basic usage of bower components (https://github.com/middleman/middleman-sprockets/commit/01176a0d676afed4c35aae3e9cd029913230e44b).

If anyone feels strongly bower support should be stronger, please re-open -- I'd lover to hear what expectations are.
