### ISSUE TITLE
Syntax error in coffeescript file requires restart to clear

### ISSUE THREAD

**Issue by joshingly** [middleman/middleman-sprockets#86]
On Ruby 2.3.0, middleman v4.0, middleman-sprockets v4.0.0.rc.1

Creating a coffeescript file with a syntax error, for example...

~~~~coffee
console.log'hi')
~~~~

Will yield the following in the console...
<img width="958" alt="screenshot 2016-01-20 21 47 06" src="https://cloud.githubusercontent.com/assets/678570/12471054/656ac766-bfbf-11e5-9d9b-6cd8e5c2c1e6.png">

The error persists after fixing the syntax error. At this point it seems the only way to get coffeescript rendering again is to restart the server.

**Comment by joshingly** [comment]
Reproduction steps / more info...

To reproduce...
- middleman init
- add middleman-sprockets (4.0.0.rc.1)
- create _entry.js.coffee in source/javascripts/ with contents: `console.log'hi')`
- load localhost:4567 to see error
- change contents of _entry.js.coffee to: `console.log 'hi'`
- reload localhost:4567

This only occurs when the syntax errors are in files prefixed with an underscore. So renaming _entry.js.coffee to entry.js.coffee fixes the issue (but will cause an entry.js file to be emitted during the build phase, which isn't the desired outcome.)

**Comment by relappi** [comment]
:+1: 

I am also seeing this issue.

**Comment by tdreyno** [comment]
And without sprockets?

**Comment by joshingly** [comment]
Without sprockets it works fine.

**Comment by tdreyno** [comment]
Thanks. So, this repo/extension is pretty much abandoned. Hopefully someone will come along who loves Sprockets enough to maintain it, but for now, it's a wasteland.

Happy to review and merge PRs, but otherwise, I'd suggest moving away from Sprockets
